package cn.com.techsure.table;
// Generated 2017-10-14 23:39:36 by Hibernate Tools 3.2.2.GA



/**
 * Hello generated by hbm2java
 */
public class Hello  implements java.io.Serializable {


     private Integer id;
     private String userName;

    public Hello() {
    }

    public Hello(String userName) {
       this.userName = userName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


