package cn.com.techsure.table;
// Generated 2017-10-14 23:39:36 by Hibernate Tools 3.2.2.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;

    public User() {
    }

    public User(String userName, String password) {
       this.userName = userName;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


